[build]
  functions = "functions"  # Folder containing your function files
  publish = "build"               # Path to static files (if any)

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
